BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: '10'
            multiline: False
            font_size: 48
        Button:
            text: 'Square'
            on_press: app.square_number(int(input_number.text))
        Label:
            id: output_label
            color: 255, 105, 180, 1
            font_size: 48
    Label:
        text: 'Enter a number and press "Square"'
